### ISSUE TITLE
[Bug] ElixirGoogleCrawler.Crawler.Core.run/1 prints non-stop errors

### ISSUE THREAD

**Issue by olivierobert** [giangnt41/elixir-google-crawler#6]
## Issue

Upon uploading the following CSV file (notice the empty line break):

```csv
reactjs
flights
hotels

```

The console log filled up with the following output:

![Screenshot 2566-03-21 at 10 25 10](https://user-images.githubusercontent.com/696529/226518683-f04854f6-f9d9-49a3-ad5b-0091177055ba.png)

## Expected

Errors and exceptions must be handled to avoid blocking the web server threads.

**Comment by giangnt41** [comment]
I have fixed it by filtering all the empty keywords, please check it out here: https://github.com/giangnt41/elixir-google-crawler/commit/d9ccd36fe57be8e105e253e7acab431c6e0e1ffc
