### ISSUE TITLE
[Question] Why not using module aliases?

### ISSUE THREAD

**Issue by olivierobert** [giangnt41/elixir-google-crawler#7]
## Issue

[~~Import~~ Alias](https://elixir-lang.org/getting-started/alias-require-and-import.html#import) is not used in any modules. Let's take for instance https://github.com/giangnt41/elixir-google-crawler/blob/master/lib/elixir_google_crawler/crawler/core.ex

An alternative approach would be the following:

```
defmodule ElixirGoogleCrawler.Crawler.Core do
  alias ElixirGoogleCrawler.Crawler.HtmlParser
  alias ElixirGoogleCrawler.Keywords.Detail

  def run(%{user_id: user_id, keyword: keyword}) do
    keyword
    |> search()
    |> HtmlParser.run()
    |> Map.put(:user_id, user_id)
    |> Detail.insert()
  end
end
```

It might make it easier to read 😁

**Comment by giangnt41** [comment]
Using the full module name is my personal preference. In case the code file is long, large, and uses many functions from different modules, the full module name is easier for developers to understand the details of the context, such as where those functions come from.

While ```import``` will include all functions from the other module, in this case, I suggest using ```alias```. It satisfies your desire to make the code easier to read.

The above code could be like:

```
defmodule ElixirGoogleCrawler.Crawler.Core do
  alias ElixirGoogleCrawler.Crawler.HtmlParser
  alias ElixirGoogleCrawler.Keywords.Detail

  def run(%{user_id: user_id, keyword: keyword}) do
    keyword
    |> search()
    |> HtmlParser.run()
    |> Map.put(:user_id, user_id)
    |> Detail.insert()
  end
end
```

**Comment by olivierobert** [comment]
Got it. I meant `aliases` initially 😅 

>  the full module name is easier for developers to understand the details of the context

Understood. However, it comes down to having a proper name for each module. The module's complete nested structure should not be used as a crutch for the module name. 

For instance, I get that for`ElixirGoogleCrawler.Keywords.Detail` using `Detail` would not be great but the root issue is that the module name `Detail` is not descriptive enough. In that case, using `ElixirGoogleCrawler.Keywords.Keyword` or ``ElixirGoogleCrawler.Keywords.KeywordDetail` would allow to use aliases without losing any clarity.

**Comment by giangnt41** [comment]
Okay I got it, I will improve it this way.

**Comment by giangnt41** [comment]
I have improved it, you can check it out here: https://github.com/giangnt41/elixir-google-crawler/commit/a29216e9e83855660df1789f4e1f477e5795871d
