### ISSUE TITLE
[Question] Why using a custom GenServer over Oban?

### ISSUE THREAD

**Issue by olivierobert** [giangnt41/elixir-google-crawler#8]
## Issue

The background processing of the keyword scraping is a bit complex to wrap one's head around as it is spread between https://github.com/giangnt41/elixir-google-crawler/blob/master/lib/elixir_google_crawler/crawler/starter.ex and https://github.com/giangnt41/elixir-google-crawler/blob/master/lib/elixir_google_crawler/crawler/core.ex. It also presents some bugs (see #6 🙈 ). So I wonder why not use a tool such as https://github.com/sorentwo/oban for background job processing

**Comment by giangnt41** [comment]
I have heard of Oban, but I have never used it before. So, when I was looking for a solution to this problem, it didn't come to mind. My bad.

Do you want me to implement it?

**Comment by olivierobert** [comment]
That would be a drastic change at this stage of the process. So there's no need for any more implementation. I wanted to understand better your reasoning process.
