### ISSUE TITLE
[Chore] Restructure HtmlParser

### ISSUE THREAD

**Issue by olivierobert** [giangnt41/elixir-google-crawler#9]
## Issue

https://github.com/giangnt41/elixir-google-crawler/blob/master/lib/elixir_google_crawler/crawler/html_parser.ex has the following room for improvement:

- keyword could be omitted in https://github.com/giangnt41/elixir-google-crawler/blob/c2d55f54e2c827a99d7b74399c8eb04ffd3550e6/lib/elixir_google_crawler/crawler/html_parser.ex#L2 since it is not used but simply returned
- It is confusing why some methods return a strong while others a map
- Re-using `run` for each method name makes it confusing and it might been an overuse of the overloading feature of Elixir 🙈

## Expected

The code could be improved along the following lines:

```elixir
defmodule ElixirGoogleCrawler.Crawler.HtmlParser do
  def run(html_document) do
      with {:ok, document} <- Floki.parse_document(response_body) do
         %{
             html: document
         }
         |> extract_total_results(document)
         |> extract_search_time(document)
         |> extract_total_urls(document)
         |> extract_total_advertisers(document)
     else 
        # some error handling if Floki cannot parse the document
     end
  end

  def extract_total_results(scraped_data, document) do
     # parsing logic

    %{scraped_data | total_results: total_results}
  end

   # other methods
end
``` 

Let me know what you think 😁

**Comment by giangnt41** [comment]
I love Elixir's pattern matching feature so much that I didn't even realize I was overusing it :) I really need to improve my mindset, thank you for that.

By the way, I have reconstructed ```ElixirGoogleCrawler.Crawler.HtmlParser``` here: https://github.com/giangnt41/elixir-google-crawler/commit/604f160002d282ac854bc6c1398d9994733882a3
